#!/bin/sh

lf=test.log

STOP_ADDRESS="0xFFF0"
XRAM_SIZE="256"

for f in *.hex; do
    name=$(basename ${f} .hex)

    echo "Testing ${name}" > ${lf}
    ../src/emu8051-cli -d 2 --xram=${XRAM_SIZE} -s ${STOP_ADDRESS} ${f} >> ${lf}
    if $? -ne 0; then
        return 1
    fi

    while read line; do
        if echo ${line} | grep -q "; Test output"; then
            test_str=$(echo ${line} | sed "s/^; Test output[0-9]: //")

            if ! grep -q "${test_str}" ${lf}; then
                echo "Failed test: ${test_str}" >> ${lf}
                exit 1
            fi
        fi
    done < ${name}.asm

done

exit 0
