#ifndef _GTKSIZES_HPP_
#define _GTKSIZES_HPP_

#define NUMBER_OF_BUTTONS  5
#define BUTTON_WIDTH       60
#define BUTTON_HEIGHT      60
#define BUTTONS_BAR_WIDTH  (NUMBER_OF_BUTTONS * BUTTON_WIDTH)
#define BUTTONS_BAR_HEIGHT BUTTON_HEIGHT

#define REG_WIN_WIDTH      100
#define REG_WIN_HEIGHT     390

#define PGM_WIN_WIDTH      480
#define PGM_WIN_HEIGHT     390

#define MEM_WIN_WIDTH      590
#define MEM_WIN_HEIGHT     280

#define MENU_BAR_HEIGHT    0

#define MAIN_WIN_WIDTH     (REG_WIN_WIDTH + PGM_WIN_WIDTH)
#define MAIN_WIN_HEIGHT    (BUTTONS_BAR_HEIGHT + REG_WIN_HEIGHT + MEM_WIN_HEIGHT)

#endif
